# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7'

env:
    matrix:
        - DJANGO=Django==1.6.10
        - DJANGO=Django==1.7.6

install:
    - if [[ $DJANGO == Django==1.6.10 ]]; then pip install south==1.0.2; fi
    - pip install $DJANGO -e . --download-cache $HOME/.pip-cache

script:
    - make test
